### ISSUE TITLE
Setup: Configure Tailwind CSS v4 design system

### ISSUE THREAD

**Issue by ccarella** [ccarella/currents#3]
## Description
Configure the Tailwind CSS v4 design system with custom colors, typography, and layout constraints according to the design specifications.

## Acceptance Criteria
- [ ] Custom color palette configured
- [ ] Typography scale set up with specified fonts
- [ ] CSS variables created for theming
- [ ] Base styles applied
- [ ] Maximum content width constraint implemented

## Implementation Steps
1. Update `globals.css` with CSS variables:
   ```css
   :root {
     --background: #FAFAF9;
     --text-primary: #1A1A1A;
     --text-secondary: #6B6B6B;
     --accent: #0066CC;
     --border: #E5E5E5;
     --surface: #FFFFFF;
   }
   ```
2. Configure custom fonts:
   - Add Inter for headlines
   - Add Charter/Spectral for body text
   - Add JetBrains Mono for code
3. Set base font size to 18px
4. Configure max content width (650px)
5. Add utility classes for common patterns

## Testing Instructions
1. Create a test page with various typography elements
2. Verify colors are applied correctly in both light/dark modes
3. Check that max-width constraint works on content
4. Test responsive behavior on mobile devices
5. Ensure custom fonts load properly
