### ISSUE TITLE
Enhancement: Add mobile-optimized responsive design

### ISSUE THREAD

**Issue by ccarella** [ccarella/currents#37]
## Description
Ensure the entire application is fully responsive and provides an excellent experience on mobile devices.

## Acceptance Criteria
- [ ] Touch-friendly tap targets
- [ ] Responsive typography scaling
- [ ] Mobile-optimized navigation
- [ ] Swipe gestures for editor
- [ ] Proper viewport configuration
- [ ] iOS safe area handling

## Implementation Steps
1. Update global styles for mobile:
   ```css
   /* Base font size scaling */
   html {
     font-size: 16px;
   }
   
   @media (min-width: 768px) {
     html {
       font-size: 18px;
     }
   }
   
   /* Safe area handling */
   .container {
     padding-left: max(1rem, env(safe-area-inset-left));
     padding-right: max(1rem, env(safe-area-inset-right));
   }
   ```
2. Create mobile navigation:
   ```typescript
   export function MobileNav() {
     const [open, setOpen] = useState(false)
     
     return (
       <>
         <button onClick={() => setOpen(true)} className="md:hidden">
           <MenuIcon />
         </button>
         
         {open && (
           <div className="fixed inset-0 z-50 bg-background">
             {/* Full screen mobile menu */}
           </div>
         )}
       </>
     )
   }
   ```
3. Optimize editor for mobile
4. Add touch gesture support
5. Test on various devices

## Testing Instructions
1. Test on iPhone Safari (notch handling)
2. Test on Android Chrome
3. Verify tap targets are 44px minimum
4. Test landscape orientation
5. Check editor usability on mobile
6. Verify no horizontal scroll
